language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
script: pytest

jobs:
  include:
  - stage: deploy
    if: tag IS present
    python: 3.5
    script: "./deploy.sh"

pypi:
  password:
    secure: mqTOeuRWRhjJ9MjJ/iGoMUaDNOC/DqR1YcG0drZKO8Y0vZ5z5FFEK/p8qFw5c8Y8iydn7F4nglEnXXUONzR0l1q4PkPgUpaOGya+Ko/GtLPtA1jqul2VPUA5M9FzCqesnWYWhpLBeUzonrIFS+WQBVFgVzWQylhlE/7xQh0zh/iTY9DQFJ6Ou63VBR8P3rpFVuvGZJVa7+KpTNUAtDxxmOhsfnR14anheBaHdf3kjhOLRcYSRdA58xJrrarvPCR7zvTtelBfLv7b4GqBknMa3F3ph/mJR7BEBjrS0zVbfKg9eRYi97x7zx35nOHe+6AJAGvFjDg/0vtddiu+/UA7SDu6YVsZxIHdkdgXoK9nbcp3MDbpHE3s6TNjMTvE562sh5cUZfVJel2sX4aBv2Lq1QwU2N7nr1oa69fwZX3hEh7FpRdSZSBDEWe/Fsho2hTCew/NuTs1Y9dZrU6/LiqEW7j7rFZqJM9qxwEJ0+YwBzjCpdV9yWK+jg0TGJDWo+y7EkJZvzwXUTtv9vDQGDRkXv4/JWqu4PFFMB0v3UWPd5ZZM2/NDv+dzFD7yJ5aIe6JhowDJLjVVvBeRKJl1ViAX0qXa9gnuaRb1PdL0YSlWIZRMdkt08MdNSontME2K6KeKQtBCeOX3JzfgnrUbsexhqUqBSOQQomodK9v0kuVM7I=
